create table [dbo].[DimCustomer](
	[CustomerKey] [int] identity(1,1) not null,
	[GeographyKey] [int] null,
	[CustomerAlternateKey] [nvarchar](15) not null,
	[Title] [nvarchar](8) null,
	[FirstName] [nvarchar](50) null,
	[MiddleName] [nvarchar](50) null,
	[LastName] [nvarchar](50) null,
	[NameStyle] [bit] null,
	[BirthDate] [date] null,
	[MaritalStatus] [nchar](1) null,
	[Suffix] [nvarchar](10) null,
	[Gender] [nvarchar](1) null,
	[EmailAddress] [nvarchar](50) null,
	[YearlyIncome] [money] null,
	[TotalChildren] [tinyint] null,
	[NumberChildrenAtHome] [tinyint] null,
	[EnglishEducation] [nvarchar](40) null,
	[SpanishEducation] [nvarchar](40) null,
	[FrenchEducation] [nvarchar](40) null,
	[EnglishOccupation] [nvarchar](100) null,
	[SpanishOccupation] [nvarchar](100) null,
	[FrenchOccupation] [nvarchar](100) null,
	[HouseOwnerFlag] [nchar](1) null,
	[NumberCarsOwned] [tinyint] null,
	[AddressLine1] [nvarchar](120) null,
	[AddressLine2] [nvarchar](120) null,
	[Phone] [nvarchar](20) null,
	[DateFirstPurchase] [date] null,
	[CommuteDistance] [nvarchar](15) null,
)